#!/bin/bash

# Function to show usage
usage() {
    echo "Usage: $0 --output output_extension [--input input_extension]"
    exit 1
}

# Check for minimum number of arguments
if [ "$#" -lt 2 ]; then
    usage
fi

# Default values
input_extension="*"
output_extension=""

# Parse command line arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --output) output_extension="$2"; shift ;;
        --input) input_extension="*.$2"; shift ;;
        *) usage ;;
    esac
    shift
done

# Validate output extension
if [ -z "$output_extension" ]; then
    echo "Output extension is required."
    usage
fi

# Convert files
echo "Starting file conversion to .$output_extension..."
for file in $input_extension; do
    if [ -f "$file" ]; then
        # Convert HEIC to JPG first, handle both lowercase and uppercase extensions
        if [[ "${file,,}" == *.heic ]]; then  # The ,, operator converts the variable to lowercase
            # Convert HEIC to JPG first
            jpg_file="${file%.*}.jpg"
            heif-convert "$file" "$jpg_file"
            file="$jpg_file"
        fi
        output_file="${file%.*}.$output_extension"
        ffmpeg -y -i "$file" "$output_file"
        if [ $? -eq 0 ] && [ -f "$output_file" ]; then
            echo "Successfully converted $file to $output_file"
        else
            echo "Failed to convert $file"
        fi
    fi
done
