#!/bin/bash

if [ -z "$1" ]
then
    echo "usage (in your api root dir):"
    echo "cptypes client_root_dir"
else

    OUT="$1/src/types"

    [ ! -d "$OUT" ] && mkdir "$OUT"

    cp -r ./dist/types/src/class/* $OUT/server/class
    cp -r ./src/types/shared/* $OUT/server/

    echo 'ok'

fi
