#!/bin/bash

command -v java >/dev/null 2>&1 || { echo >&2 "I require 'java' but it's not installed. Installing now..."; sudo apt install -y default-jre; }

keytool -genkeypair -alias upload -keyalg RSA -keysize 2048 -validity 9125 -keystore keystore.jks   
keytool -export -rfc -keystore keystore.jks -alias upload -file upload_certificate.pem